version: '2'
services:
  erp-registry:
    image: ghacupha/erp-registry:0.0.1-SNAPSHOT
    volumes:
      - ./central-server-config:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger,uaa
      - SPRING_SECURITY_USER_PASSWORD=${ERP_REGISTRY_PASSWORD}
      - JHIPSTER_REGISTRY_PASSWORD=${ERP_REGISTRY_PASSWORD}
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
      - ERP_REGISTRY_PORT=${ERP_REGISTRY_PORT}
      - ERP_REGISTRY_PASSWORD=${ERP_REGISTRY_PASSWORD}
      - ERP_REGISTRY_USERNAME=${ERP_REGISTRY_USERNAME}
      - SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${SECURITY_AUTHENTICATION_JWT_BASE64_SECRET}
    ports:
      - 8761:8761
