version: '2'
services:
  payment-records-app:
    image: ghacupha/payment-records:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/${PAYMENT_RECORDS_PROD_DB}
      - JHIPSTER_SLEEP=60 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=${SPRING_DATA_JEST_URI}
      - SPRING_ELASTICSEARCH_REST_URIS=${SPRING_DATA_JEST_URI}
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
      - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
      - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
      - PAYMENT_RECORDS_PROD_DB=${PAYMENT_RECORDS_PROD_DB}
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - PAYMENT_RECORDS_DEV_DB=${PAYMENT_RECORDS_DEV_DB}
      - JHIPSTER_REGISTRY_PASSWORD=${JHIPSTER_REGISTRY_PASSWORD}
      - PAYMENT_RECORDS_PORT=${PAYMENT_RECORDS_PORT}
  paymentrecords-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: paymentrecords-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/

  payment-records-gate-app:
    image: ghacupha/payment-records-gate:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/${PAYMENT_RECORDS_GATE_PROD_DB}
      - PAYMENT_RECORDS_GATE_PORT=${PAYMENT_RECORDS_GATE_PORT}
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
      - PAYMENT_RECORDS_GATE_PROD_DB=${PAYMENT_RECORDS_GATE_PROD_DB}
      - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
      - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
      - PAYMENT_RECORDS_GATE_DEV_DB=${PAYMENT_RECORDS_GATE_DEV_DB}
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
    ports:
      - 8791:8791