name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: Payment Records pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            DOCKER_IMAGE_PREFIX: ${{ secrets.DOCKER_IMAGE_PREFIX }}
            PAYMENT_RECORDS_PORT: ${{ secrets.PAYMENT_RECORDS_PORT }}
            PAYMENT_RECORDS_DEV_DB: ${{ secrets.PAYMENT_RECORDS_DEV_DB }}
            PAYMENT_RECORDS_PROD_DB: ${{ secrets.PAYMENT_RECORDS_PROD_DB }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Login to Docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean verify
            - name: Package application
              run: ./mvnw -ntp package -Pprod -DskipTests
            - name: Build and publish docker image
              if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
              run: |
                  ./mvnw -ntp jib:build -Djib.to.image=ghacupha/payment-records:0.0.1-SNAPSHOT -Djib.to.auth.username="${{secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{secrets.DOCKER_PASSWORD }}"
