name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: Payment Records Gate pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
            PAYMENT_RECORDS_GATE_PORT: ${{ secrets.PAYMENT_RECORDS_GATE_PORT }}
            DOCKER_IMAGE_PREFIX: ${{ secrets.DOCKER_IMAGE_PREFIX }}
            PAYMENT_RECORDS_GATE_DEV_DB: ${{ secrets.PAYMENT_RECORDS_GATE_DEV_DB }}
            PAYMENT_RECORDS_GATE_PROD_DB: ${{ secrets.PAYMENT_RECORDS_GATE_PROD_DB }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Install node.js packages
              working-directory: ./payment-records-gate
              run: npm install
            - name: Run backend test
              working-directory: ./payment-records-gate
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean verify -P-webpack
            - name: Run frontend test
              working-directory: ./payment-records-gate
              run: npm run test
            - name: Package application
              working-directory: ./payment-records-gate
              run: ./mvnw -ntp package -Pprod -DskipTests
            - name: Build and publish docker image
              working-directory: ./payment-records-gate
              if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
              run: |
                  ./mvnw -ntp jib:build -Djib.to.image=ghacupha/payment-records-gate:0.0.1-SNAPSHOT -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}"
